version: '3.8'

services:
  fhir-ru:
    image: healthsamurai/fhir-ru:latest
    restart: unless-stopped
    pull_policy: always
    volumes:
      - ./keystore:/app/keystore
      - /root/.ssh:/root/.ssh
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8082:8082"
      - "127.0.0.1:8083:8083"
      - "127.0.0.1:8084:8084"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    command: --schedule "0 */5 * * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
