version: '3.8'

services:
  fhir-ru:
    image: healthsamurai/fhir-ru:latest
    restart: unless-stopped
    pull_policy: always
    volumes:
      - ./keystore:/app/keystore
      - ~/.ssh:~/.ssh
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    command: --schedule "0 */5 * * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
